# Generated by Django 5.2.7 on 2025-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="break_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="is_break",
            field=models.BooleanField(default=False),
        ),
    ]
