# Generated by Django 5.2.7 on 2025-10-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("timetables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="accounts.school",
            ),
        ),
    ]
