# Generated by Django 5.2.7 on 2025-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0002_timeslot_break_name_timeslot_is_break"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="break_name",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="day",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="name",
            field=models.CharField(default="Lesson", max_length=50),
        ),
    ]
