# Generated by Django 5.2.7 on 2025-10-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0003_remove_timeslot_break_name_remove_timeslot_day_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
