# Generated by Django 5.2.7 on 2025-11-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetables",
            "0003_faqcategory_howitworksstep_serviceplan_testimonial_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="howitworksstep",
            name="subtitle",
        ),
    ]
