# Generated by Django 5.2.7 on 2025-11-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0004_remove_howitworksstep_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceplan",
            name="button_text",
        ),
        migrations.RemoveField(
            model_name="serviceplan",
            name="button_url",
        ),
    ]
