# Generated by Django 5.2.7 on 2025-11-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetables", "0005_remove_serviceplan_button_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceplan",
            name="description",
        ),
    ]
